"""Compatibility facade for report generation helpers.

Implementation lives under :mod:`bubble_index.report`; this module keeps older
imports such as ``from bubble_index.reporting import write_outputs`` working.
"""

from __future__ import annotations

from .report import (
    BUBBLE_STAGE_NOTES,
    BUBBLE_STAGE_YEARS,
    HISTORICAL_REFERENCE_STAGES,
    build_summary,
    chart_number,
    copy_static_assets,
    factor_reason,
    find_stage_points,
    format_axis_number,
    format_decimal,
    format_plain_percent,
    format_score,
    format_signed_percent,
    future_max_drawdown,
    historical_reference_cards,
    interactive_chart_bootstrap,
    interactive_chart_payload,
    latest_complete_row,
    nearest_index_position,
    previous_complete_row,
    previous_score_caption,
    project_root,
    render_backtest_section,
    render_html_report,
    render_interactive_charts,
    render_reference_section,
    render_stage_chips,
    risk_label,
    scaled_index_series,
    script_json,
    static_assets_dir,
    svg_index_chart,
    svg_line_chart,
    svg_score_gauge,
    trim_frame_to_range,
    trim_to_recent_years,
    write_outputs,
    x_axis_ticks,
)

__all__ = [
    "BUBBLE_STAGE_NOTES",
    "BUBBLE_STAGE_YEARS",
    "HISTORICAL_REFERENCE_STAGES",
    "build_summary",
    "chart_number",
    "copy_static_assets",
    "factor_reason",
    "find_stage_points",
    "format_axis_number",
    "format_decimal",
    "format_plain_percent",
    "format_score",
    "format_signed_percent",
    "future_max_drawdown",
    "historical_reference_cards",
    "interactive_chart_bootstrap",
    "interactive_chart_payload",
    "latest_complete_row",
    "nearest_index_position",
    "previous_complete_row",
    "previous_score_caption",
    "project_root",
    "render_backtest_section",
    "render_html_report",
    "render_interactive_charts",
    "render_reference_section",
    "render_stage_chips",
    "risk_label",
    "scaled_index_series",
    "script_json",
    "static_assets_dir",
    "svg_index_chart",
    "svg_line_chart",
    "svg_score_gauge",
    "trim_frame_to_range",
    "trim_to_recent_years",
    "write_outputs",
    "x_axis_ticks",
]
